[versions]
axion = "1.13.3"
dependencycheck = "10.0.3"
guava = "33.3.0-jre"
jakarta-annotation-api = "3.0.0"
jena = "5.3.0"
junit = "5.11.0"
logback = "1.5.7"
lombok = "8.10"
spring = "6.2.1"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation-api" }
jena-arq = { module = "org.apache.jena:jena-arq", version.ref = "jena" }
jena-fuseki-main = { module = "org.apache.jena:jena-fuseki-main", version.ref = "jena" }
jena-tdb2 = { module = "org.apache.jena:jena-tdb2", version.ref = "jena" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[bundles]

[plugins]
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion" }
dependencycheck = { id = "org.owasp.dependencycheck", version.ref = "dependencycheck" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }